"""Create database, add tables to define users and custom user fields.

Revision ID: f89daeeb3ae7
Revises: a484f787504c
Create Date: 2025-10-16 20:23:51.011293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f89daeeb3ae7'
down_revision: Union[str, Sequence[str], None] = 'a484f787504c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_type_definitions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('field_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_type_definitions_name'), 'user_type_definitions', ['name'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=True),
    sa.Column('custom_type_definition_id', sa.UUID(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['custom_type_definition_id'], ['user_type_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_custom_type_definition_id'), 'users', ['custom_type_definition_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('military_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=255), nullable=True),
    sa.Column('mos', sa.String(length=50), nullable=True),
    sa.Column('branch', sa.Enum('ARMY', 'NAVY', 'AIR_FORCE', 'MARINES', 'SPACE_FORCE', 'COAST_GUARD', name='militarybranch'), nullable=True),
    sa.Column('service_number', sa.String(length=50), nullable=True),
    sa.Column('clearance_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_military_users_service_number'), 'military_users', ['service_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_military_users_service_number'), table_name='military_users')
    op.drop_table('military_users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_custom_type_definition_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_type_definitions_name'), table_name='user_type_definitions')
    op.drop_table('user_type_definitions')
    # ### end Alembic commands ###
